### ISSUE TITLE
Regular expression to "placement"

### ISSUE THREAD

**Issue by yuyou** [MPEGGroup/NBMP#11]
Current expression allows lower-case chars. How about upper case? like [A-Z]?

https://github.com/MPEGGroup/NBMP/blob/fced99301ad162967bdc42a53224fa569ea9a04e/nbmp-schema-definitions.json#L596

**Comment by irajs** [comment]
Good point. Should it be the following?
"pattern": "^(([a-z]|[A-Z]){2}$)|(([a-z]|[A-Z]){2}-.*$)"

**Comment by yuyou** [comment]
Actually I meant to change lowercase to uppercase, like
`^(([A-Z]){2}$)|(([A-Z]){2}-.*$)`

**Comment by irajs** [comment]
OK. It makes sense. I update the schema w this.

**Comment by irajs** [comment]
Addressed.
