### ISSUE TITLE
"anyOf" vs "OneOf"

### ISSUE THREAD

**Issue by yuyou** [MPEGGroup/NBMP#13]
JSON Schema defines:

- allOf: Must be valid against all of the subschemas
- anyOf: Must be valid against any of the subschemas
- oneOf: Must be valid against exactly one of the subschemas

For example, a description may have situations with 1) single media input; 2) single metadata input; 3) media and metadata inputs. 

Based on that, the appropriate choice of the combining keyword may be "anyOf", not "oneOf". Propose to change to "anyOf".

https://github.com/MPEGGroup/NBMP/blob/d8bf3658c381139f24b30b87d9ec0038246b11f0/nbmp-schema-definitions.json#L136

https://github.com/MPEGGroup/NBMP/blob/d8bf3658c381139f24b30b87d9ec0038246b11f0/nbmp-schema-definitions.json#L261

**Comment by irajs** [comment]
Addressed in the latest pull request.
