### ISSUE TITLE
All $ref values miss "#" anchor sign

### ISSUE THREAD

**Issue by yuyou** [MPEGGroup/NBMP#22]
https://github.com/MPEGGroup/NBMP/blob/6971da8ca13335a01e3a0fa85013599fdfb50592/nbmp-task-schema.json#L9

JSON schema uses "$ref" to reference to external schema definitions. It uses "#" anchor sign, e.g.

Local reference:

`"$ref": "#/definitions/local_schema_definiton"`

Remote/external reference:

`"$ref": "document.json#/myElement"`
`"$ref": "http://dummy.org/document.json#/myElement"`

References:
* https://swagger.io/docs/specification/using-ref/

**Comment by irajs** [comment]
Thank you for correcting the mistakes. Really appreciated. Fixed.
