### ISSUE TITLE
Typo in schema definitions

### ISSUE THREAD

**Issue by mlasak** [MPEGGroup/NBMP#23]
IS:  
`"pattenrProperties":{
          "^urn:mpeg:mpegi:nbmp:v": {"type" : "string"}
        },`
SHOULD BE:
`"pattern":"^urn:mpeg:mpegi:nbmp:v"`

https://github.com/MPEGGroup/NBMP/blob/ce4b7a983b507019a4d9e114089cf4f67a8283a6/nbmp-schema-definitions.json#L44

**Comment by irajs** [comment]
Thank you! fixed.
