### ISSUE TITLE
Error in Processing Descriptor Schema

### ISSUE THREAD

**Issue by mlasak** [MPEGGroup/NBMP#25]
For array declarations like `connection-map.items`: items property must be specified as an object (not array)

Wrong [here](https://github.com/MPEGGroup/NBMP/blob/ce4b7a983b507019a4d9e114089cf4f67a8283a6/nbmp-schema-definitions.json#L436) and [here](https://github.com/MPEGGroup/NBMP/blob/ce4b7a983b507019a4d9e114089cf4f67a8283a6/nbmp-schema-definitions.json#L504)

**Comment by irajs** [comment]
Thank you for the catch! Fixed.
