### ISSUE TITLE
Error in Requirements Descriptor Schema

### ISSUE THREAD

**Issue by mlasak** [MPEGGroup/NBMP#26]
Wrong syntax in schema for resource-estimators attribute

IS:
`
            "items": {
              "name" : {"type": "string"},
              "value": {"type": "string"}
            }
`

Correct would be:
`
                    "items": {
                        "type" : "object",
                        "properties" : {
                           "name" : {"type" : "string"},
                           "value" : {"type" : "string"}
                        }
                     }
`

Wrong [here](https://github.com/MPEGGroup/NBMP/blob/ce4b7a983b507019a4d9e114089cf4f67a8283a6/nbmp-schema-definitions.json#L645)

**Comment by irajs** [comment]
Fixed. Thank you!
