### ISSUE TITLE
Variables Descriptor Schema incorrect

### ISSUE THREAD

**Issue by mlasak** [MPEGGroup/NBMP#27]
Variables Descriptor Schema does not validate against https://json-schema.org/draft/2019-09/schema

Probably, this [two](https://github.com/MPEGGroup/NBMP/blob/ce4b7a983b507019a4d9e114089cf4f67a8283a6/nbmp-schema-definitions.json#L899) [lines](https://github.com/MPEGGroup/NBMP/blob/ce4b7a983b507019a4d9e114089cf4f67a8283a6/nbmp-schema-definitions.json#L928) must be removed.

**Comment by irajs** [comment]
thank you. Fixed.
