### ISSUE TITLE
some of those parameters are no longer used

### ISSUE THREAD

**Issue by yuyou** [MPEGGroup/NBMP#6]
Three [parameters](          https://github.com/MPEGGroup/NBMP/blob/a857bfc109475b6891b080530d0b65f1b7f585d4/nbmp-schema-definitions.json#L576-L587) under "hardware-requirements" are no longer needed.
They are: 

1. processor-requirement
1. cpu-cores
1. gpu

**Comment by irajs** [comment]
I agree. Removed them from Spec & schema.
